---
abstract: 'subroutine definitions with parameter lists'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Function-Parameters
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://git.shadowcat.co.uk/p5sagit/Function-Parameters
version: 0.09
