--- #YAML:1.0
name:               Function-Parameters
version:            0.03
abstract:           subroutine definitions with parameter lists
author:
    - Lukas Mai <l.mai@web.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    B::Compiling:         0
    B::Hooks::EndOfScope:  0
    Devel::Declare:       0
    strict:               0
    Test::More:           0
    warnings:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
