---
abstract: 'subroutine definitions with parameter lists'
author:
  - 'Lukas Mai <l.mai@web.de>'
build_requires:
  Dir::Self: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Function-Parameters
no_index:
  directory:
    - t
    - inc
requires:
  B::Hooks::EndOfScope: 0
  Carp: 0
  XSLoader: 0
  bytes: 0
  perl: 5.014000
  strict: 0
  warnings: 0
version: 0.05_02
